### ISSUE TITLE
Target .NET Standard 1.2

### ISSUE THREAD

**Issue by inforithmics** [JamesNK/Newtonsoft.Json.Bson#6]
I wanted to use Newton.Json.Bson nuget package in a project Targeting Windows 8.1 Store App. But Newtonsoft.Json.Bson Targets the .NET Standard 1.3 so I can't use it. Because only .NET Standard 1.2 is supported.

So my question is there a reason why .NET Standard 1.3 was used and if not can Newtonsoft.Json.Bson be retargeted to .Net Standard 1.2

**Comment by solvingJ** [comment]
I can't say for sure, but since nobody has answered this I'll wager a guess.  It's likely because System.Runtime.Serialization.Formatters was not available until .NET Standard 1.3, and Json.NET references this package to provide support for the very widely used ISerializable interface.  

I have no idea whether it will be retargeted for 1.2 with this support removed, but I did find this: 

https://www.nuget.org/packages/CoreCompat.Newtonsoft.Json/

You might try that?

**Comment by inforithmics** [comment]
Thanks for the Info. But for me it is easier just to use the regular json.net library without BSON support and serialize with JSon.

As a side note the consenus seems to be to use at least .NET Standard 1.3 for newer projects and I think I have to migrate there and handle Windows 8.1 as special case / legacy platform with less functionality. And for the other platforms use at least .NET Standard 1.3.
